### ISSUE TITLE
Required detections and segmentations

### ISSUE THREAD

**Issue by gcaldarulo7** [aleksandrkim61/EagerMOT#11]
Hi, I'm trying to run the code as a state of the art reference for my master thesis work, and I was trying to run it with 3D PointGNN + (2D MOTSFusion+RRC) using KITTI and no other detections/segmentations so I thought I should comment the lines referring to other possibilities in the inputs/utils.py file, but when I run the code it stops due to not having TRACKRCNN data. How should I handle this? do I need those files aswell?

**Comment by aleksandrkim61** [comment]
Hi,

Can you provide more information? Ideally the stack trace to see where exactly it fails and what it requests. I tried to find where it might need TrackRCNN data, but did not find a reference.

Did you run `adapt_kitti_motsfusion_input.py` as written in the **NOTE** in the README? Without it, the detections lack some information and one of the functions will throw an error as commented [here](https://github.com/aleksandrkim61/EagerMOT/blob/3733e6070e7ac644315d28c1c5c4c525cce64746/inputs/detections_2d.py#L69).

If you need it urgently, then just download TrackRCNN data as well and run the code. It should not use TrackRCNN and it must just be some extra reference or wrong error message in the code.

**Comment by gcaldarulo7** [comment]
I managed to solve the issue but wanted to ask something about the outputs of the algorithm. 
For each object there is an ID, the class to which it belongs, 7 integer numbers which seem to be always equal between objects and the boundin box right?
[0000.txt](https://github.com/aleksandrkim61/EagerMOT/files/7328650/0000.txt)
n

**Comment by aleksandrkim61** [comment]
Yes, there are seven integers that are static and are not used for 3D MOT evaluation, all output params are defined [here](https://github.com/pratikac/kitti/blob/eba7ba0f36917f72055060e9e59f344b72456cb9/readme.tracking.txt#L54) 
* three first ones are truncated, occluded, alpha, which are never evaluated, I think.
* the other four are coordinates for 2D bounding boxes in the camera frame, which are only used for 2D MOT evaluation.

In the other output folder with suffix "2d_projected_3d" you will find output files where the values used in 3D MOT are all -1 and the 2D coordinates are visible. This is because KITTI evaluates 2D and 3D MOT results separately, so the code also produces two sets of results.
