### ISSUE TITLE
Tracking on nuscenes data with centerpoint 3d detections on nuscenes and mmdetection cascade on nuimages

### ISSUE THREAD

**Issue by gayathri81** [aleksandrkim61/EagerMOT#16]
Hello @aleksandrkim61 ,
Thanks for the sharing your code.
I am trying to run tracking on **nuscenes** data with the exisiting detections provided in model zoo, but I am stuck at understanding how **nuimges** 2d detections and **nuscenes** 3d detections are correlated as the data in **nuscenes** is not same as **nuimages**.   
**mmdetection** is run on **nuimages** and **centerpoint** is run on **nuscenes** and in the code we provide the path to the **nuscenes** and only correlated I could see is the class mapping from **nuimages** to **nuscens**. It would be really great if you can help me understand this. 
Thanks,
Gayathri.

**Comment by joshphoo** [comment]
Hi @gayathri81 / @aleksandrkim61 ,

I am encountering the same issue and read your post also on the NuScenes forum (https://forum.nuscenes.org/t/is-it-possible-to-use-results-run-on-nuscenes-and-nuimages-together/689). Is there any update on this or have you managed to solve this problem?

**Comment by aleksandrkim61** [comment]
Hi, the `nuimages` in the source is just where the model was trained on. It was then ran on `nuscenes`, so the detections are made for the `nuscenes` images.
If you try to run it, it will work because the frame tokens are the same.

Sorry for the late reply, was busy with other stuff and did not get proper notifications. Check out my latest work https://polarmot.github.io/
