### ISSUE TITLE
about using AB3DMOT

### ISSUE THREAD

**Issue by russellyq** [aleksandrkim61/EagerMOT#24]
Hi Thanks for your great works !

May I ask how could I change the code if using  'AB3DMOT' ?

Thanks

**Comment by aleksandrkim61** [comment]
Change the input_source arguments in the main calling code and download corresponding data. 
But there is really no reason to use AB3DMOT since it only changes detections to older ones, which are worse. The code is only there since I used it for ablations

Sorry for the late reply, was busy with other stuff and did not get proper notifications. Check out my latest work https://polarmot.github.io/
