### ISSUE TITLE
some clarifications regarding kitti dataset

### ISSUE THREAD

**Issue by sparshgarg23** [aleksandrkim61/EagerMOT#25]
Hi,
Thanks for open sourcing the work,I am interested in running some experiments using EagerMot on kitti dataset to get an understanding of how multi object tracking works.
Since kitti 2d tracking has multiple files,I just wanted to confirm that these are the necesary files which need to be downloaded
1.left color images
2.camera callibration matrices of track set
3.L-SVM reference detections
4.regionlet reference detections.

I am assuming that files 3 and 4 are not required,since the detection results are already provided right?
Apart from these files,is there anything else which i need to look into before evaluating the tracker?

**Comment by joshphoo** [comment]
Hi,

Is there any update/clarification for this? I am having the same issues right now.

**Comment by sparshgarg23** [comment]
still waiting,I had moved on to greener pastures.Seems that the author of the repository is preoccupied with other things.

**Comment by aleksandrkim61** [comment]
Hey, since we are only operating on detections themselves and not using any of the source images, you only need 2. calibration matrices.
Obviously you would need other data if you plan to generate your own detections

Sorry, was busy with other work and did not get notification emails from Github properly. Check out https://polarmot.github.io/ for the newest paper on 3D MOT :)
