### ISSUE TITLE
'class' in MOTSFusion detection/segmentation

### ISSUE THREAD

**Issue by Yu-Lei-Li** [aleksandrkim61/EagerMOT#3]
HI, 
How do you get the KEY 'class' in MOTSFusion detection/segmentation.txt/.json? I can not run the code  due to program error:   File ".../EagerMOT/inputs/detections_2d.py", line 77, in parse_motsfusion_seg
    return (int(seg_json['class']), float(seg_json['score']),
KeyError: 'class'

**Comment by zouhaoa** [comment]
Hey! Did you solve this error?

**Comment by aleksandrkim61** [comment]
Hi! The issue was closed so quickly, I did not notice it.

What you need to do is add detections information (e.g. score, class_id, etc.) to MOTSFusion segmentations if it's not already there. The functions you can use to adapt MOTSFusion input to the expected format are in `inputs/adapt_input.py`. They should work but you might need to call them from a separate script or a notebook.

I had the higher-level function as well, where you can just call it to adapt the inputs. I will look for it in the next few days and update the repo. But it definitely was straightforward, so if you don't want to wait, you can certainly make it work quickly.

**Comment by aleksandrkim61** [comment]
Looked at the code again and realized that the functionality is already in the repo!

Just pushed a quick script that should work if you run it with correctly set up paths in `inputs/utils.py`. Also added a note about it in the README. Please let me know if it does not work or close the issue again.

**Comment by Yu-Lei-Li** [comment]
yes. I solve this problem.

thank you for your help.


ZouHao ***@***.***> 于2021年6月23日周三 下午9:36写道：
