### ISSUE TITLE
Does the code require any training?

### ISSUE THREAD

**Issue by sisaha9** [aleksandrkim61/EagerMOT#5]
I am just catching up on this work. I don't see a training script set up anywhere. Can this code be modified to run real time instead of a dataset without any training beforehand?

**Comment by sisaha9** [comment]
Ah I see it relies on pre established boundary boxes. So we would provide that in a similar format. Thanks!

**Comment by aleksandrkim61** [comment]
You got it! The fact that **tracking is not coupled to any specific input source or data** is one of its big advantages. 

You do not even have to provide detections in the same exact format, you can just add a custom parser to `inputs/detections_{3d/2d}` to consume your format. That's why there are so many parsing functions - to accommodate different detection formats provided by the community that we used in our experiments.
