### ISSUE TITLE
can you provide detections data in google drive since it's hard to find in  github repo?

### ISSUE THREAD

**Issue by xiaoliangabc** [aleksandrkim61/EagerMOT#6]
can you provide following detections data?

<img width="315" alt="Screenshot 2021-07-01 at 5 57 17 PM" src="https://user-images.githubusercontent.com/33284779/124105582-ef050d00-da95-11eb-99c4-d7709daf2c6f.png">

**Comment by aleksandrkim61** [comment]
Hi,

Only the data that was not readily available and had to be generated using open source code is provided in the drive link from the README (the open source code we used is now also linked in that section).

All other data that is provided directly by the authors of those works should be downloaded directly from them. I have added a little more detail in our README on where to find their download instructions in their README files, and it should not be difficult to then follow their instructions. We want to refer readers directly to other related work and will not redistribute their data ourselves, so please go through the linked pages.
*We only included [AB3DMOT's](https://github.com/xinshuoweng/AB3DMOT) detections in the linked drive because they have changed their data format and it would be difficult to find the correct version. 

I hope the [added details](https://github.com/aleksandrkim61/EagerMOT#download-3d-and-2d-detections-which-ones-to-download-depends-on-what-you-want-to-run) help you find the data you might need. 

Note that you do not have to download all souces to run our framework, you only need a single 3D and a single 2D source for your chosen dataset. In the README, we specify which pairings were used to obtain our best results on the KITTI and NuScenes benchmarks.
